# Generated by Django 5.2.3 on 2026-03-09 23:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("store", "0002_uuid_pk_tenant_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminPIIAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        help_text="Model name of the accessed record.", max_length=100
                    ),
                ),
                (
                    "record_id",
                    models.CharField(
                        help_text="PK of the accessed record.", max_length=255
                    ),
                ),
                (
                    "accessed_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Request path that triggered PII access.",
                        max_length=500,
                    ),
                ),
                ("method", models.CharField(blank=True, default="", max_length=10)),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="store.store",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "analytics_adminpiiaccesslog",
                "ordering": ["-accessed_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "accessed_at"],
                        name="analytics_a_user_id_9cd11e_idx",
                    ),
                    models.Index(
                        fields=["store", "accessed_at"],
                        name="analytics_a_store_i_f4e84d_idx",
                    ),
                ],
            },
        ),
    ]
