# Generated by Django 5.2.17 on 2026-09-02 00:07

from decimal import Decimal
from django.db import migrations, models


def _table_exists(cursor, table_name):
    cursor.execute(
        "SELECT 1 FROM information_schema.tables WHERE table_name = %s",
        [table_name],
    )
    return cursor.fetchone() is not None


def safe_analytics_forward(apps, schema_editor):
    """Safe migration forward for analytics.0003.

    Production DB may have 0002 marked as applied but tables not created
    (interrupted deploy). This function handles all cases gracefully.
    """
    tables_to_check = [
        "analytics_aievent",
        "analytics_dailyrevenuesummary",
        "analytics_hourlyordersummary",
        "analytics_tenanthealthsnapshot",
        "analytics_storefirstorderevent",
        "analytics_adminpiiaccesslog",
    ]

    with schema_editor.connection.cursor() as cursor:
        existing = {t for t in tables_to_check if _table_exists(cursor, t)}

    # If no analytics tables exist, 0002 was never fully applied — skip entirely.
    # When 0002 eventually runs, it will create tables with the correct schema.
    if not existing:
        return

    # --- Index rename for AIEvent (only if table exists) ---
    if "analytics_aievent" in existing:
        with schema_editor.connection.cursor() as cursor:
            old_name = "idx_analytics_aievent_store_type"
            new_name = "an_aievent_store_type"

            cursor.execute("SELECT 1 FROM pg_indexes WHERE indexname = %s", [old_name])
            old_exists = cursor.fetchone() is not None
            cursor.execute("SELECT 1 FROM pg_indexes WHERE indexname = %s", [new_name])
            new_exists = cursor.fetchone() is not None

        if old_exists and not new_exists:
            schema_editor.execute(f'ALTER INDEX "{old_name}" RENAME TO "{new_name}"')
        elif not old_exists and not new_exists:
            schema_editor.execute(
                f'CREATE INDEX "{new_name}" ON "analytics_aievent" '
                f'("store_id", "event_type", "occurred_at")'
            )

    # --- AlterField operations (only on existing tables) ---
    # These are no-ops if the schema already matches (which it will if 0002
    # created the tables with the correct definitions).
    analytics_models = {
        "analytics_adminpiiaccesslog": "adminpiiaccesslog",
        "analytics_aievent": "aievent",
        "analytics_dailyrevenuesummary": "dailyrevenuesummary",
        "analytics_hourlyordersummary": "hourlyordersummary",
        "analytics_storefirstorderevent": "storefirstorderevent",
        "analytics_tenanthealthsnapshot": "tenanthealthsnapshot",
    }

    field_changes = {
        "adminpiiaccesslog": [
            ("path", models.CharField(blank=True, default="", max_length=500)),
            ("record_id", models.CharField(max_length=255)),
            ("record_type", models.CharField(max_length=100)),
        ],
        "aievent": [
            ("entity_id", models.CharField(blank=True, default="", help_text="ID of the product, search query, or order.", max_length=255)),
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
        ],
        "dailyrevenuesummary": [
            ("amount_usd", models.DecimalField(decimal_places=2, default=Decimal("0"), help_text="USD-normalized revenue for cross-tenant GMV. 1 KES ≈ 0.0078 USD.", max_digits=14)),
            ("aov", models.DecimalField(blank=True, decimal_places=2, help_text="Average order value. Null when order_count=0.", max_digits=14, null=True)),
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("top_products", models.JSONField(default=list, help_text="Top 5 products by revenue: [{product_id, name, revenue}]")),
        ],
        "hourlyordersummary": [
            ("hour", models.PositiveSmallIntegerField(help_text="Hour of day (0–23) in store's local time.")),
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
        ],
        "storefirstorderevent": [
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
        ],
        "tenanthealthsnapshot": [
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("is_healthy", models.BooleanField(default=True, help_text="False if subscription is past_due or suspended.")),
        ],
    }

    for db_table, model_name in analytics_models.items():
        if db_table not in existing:
            continue
        for field_name, field_instance in field_changes.get(model_name, []):
            try:
                model = apps.get_model("analytics", model_name)
                old_field = model._meta.get_field(field_name)
                schema_editor.alter_field(model, old_field, field_instance)
            except Exception:
                pass  # Table may not have the column yet — skip silently


def safe_analytics_backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_analytics_summaries"),
    ]

    operations = [
        migrations.RunPython(safe_analytics_forward, safe_analytics_backward),
    ]
