# Generated by Django 5.2.17 on 2026-09-02 00:07

from decimal import Decimal
from django.db import migrations, models


def safe_rename_aievent_index(apps, schema_editor):
    """Rename the index only if the old name exists and the new name doesn't."""
    table_name = "analytics_aievent"
    old_name = "idx_analytics_aievent_store_type"
    new_name = "an_aievent_store_type"

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT 1 FROM pg_indexes WHERE indexname = %s",
            [old_name],
        )
        old_exists = cursor.fetchone() is not None

        cursor.execute(
            "SELECT 1 FROM pg_indexes WHERE indexname = %s",
            [new_name],
        )
        new_exists = cursor.fetchone() is not None

    if old_exists and not new_exists:
        schema_editor.execute(
            f'ALTER INDEX "{old_name}" RENAME TO "{new_name}"'
        )
    elif not old_exists and not new_exists:
        # Neither exists — create the index fresh
        schema_editor.execute(
            f'CREATE INDEX "{new_name}" ON "{table_name}" '
            f'("store_id", "event_type", "occurred_at")'
        )
    # If new_exists, nothing to do — already correct


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_analytics_summaries"),
    ]

    operations = [
        migrations.RunPython(safe_rename_aievent_index, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="adminpiiaccesslog",
            name="path",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="adminpiiaccesslog",
            name="record_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="adminpiiaccesslog",
            name="record_type",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="aievent",
            name="entity_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="ID of the product, search query, or order.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="aievent",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="dailyrevenuesummary",
            name="amount_usd",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="USD-normalized revenue for cross-tenant GMV. 1 KES ≈ 0.0078 USD.",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="dailyrevenuesummary",
            name="aov",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Average order value. Null when order_count=0.",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dailyrevenuesummary",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="dailyrevenuesummary",
            name="top_products",
            field=models.JSONField(
                default=list,
                help_text="Top 5 products by revenue: [{product_id, name, revenue}]",
            ),
        ),
        migrations.AlterField(
            model_name="hourlyordersummary",
            name="hour",
            field=models.PositiveSmallIntegerField(
                help_text="Hour of day (0–23) in store's local time."
            ),
        ),
        migrations.AlterField(
            model_name="hourlyordersummary",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="storefirstorderevent",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="tenanthealthsnapshot",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="tenanthealthsnapshot",
            name="is_healthy",
            field=models.BooleanField(
                default=True,
                help_text="False if subscription is past_due or suspended.",
            ),
        ),
    ]
