# Generated by Django 5.2.17 on 2026-09-02 00:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_analytics_summaries"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="aievent",
            new_name="an_aievent_store_type",
            old_name="idx_analytics_aievent_store_type",
        ),
        migrations.AlterField(
            model_name="adminpiiaccesslog",
            name="path",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="adminpiiaccesslog",
            name="record_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="adminpiiaccesslog",
            name="record_type",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="aievent",
            name="entity_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="ID of the product, search query, or order.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="aievent",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="dailyrevenuesummary",
            name="amount_usd",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="USD-normalized revenue for cross-tenant GMV. 1 KES ≈ 0.0078 USD.",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="dailyrevenuesummary",
            name="aov",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Average order value. Null when order_count=0.",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dailyrevenuesummary",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="dailyrevenuesummary",
            name="top_products",
            field=models.JSONField(
                default=list,
                help_text="Top 5 products by revenue: [{product_id, name, revenue}]",
            ),
        ),
        migrations.AlterField(
            model_name="hourlyordersummary",
            name="hour",
            field=models.PositiveSmallIntegerField(
                help_text="Hour of day (0–23) in store's local time."
            ),
        ),
        migrations.AlterField(
            model_name="hourlyordersummary",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="storefirstorderevent",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="tenanthealthsnapshot",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="tenanthealthsnapshot",
            name="is_healthy",
            field=models.BooleanField(
                default=True,
                help_text="False if subscription is past_due or suspended.",
            ),
        ),
    ]
