# Generated by Django 5.2.3 on 2026-09-06 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "analytics",
            "0004_rename_idx_analytics_aievent_store_type_an_aievent_store_type_and_more",
        ),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="aievent",
            new_name="an_aievent_store_type",
            old_name="idx_analytics_aievent_store_type",
        ),
    ]
