# Generated by Django 5.2.3 — Story 2.2: MpesaTransaction model

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MpesaTransaction",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        db_index=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="store.store",
                    ),
                ),
                ("reference", models.CharField(db_index=True, max_length=100)),
                ("phone", models.CharField(max_length=20)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("STK_PUSH_INITIATED", "STK Push Initiated"),
                            ("CONFIRMED", "Confirmed"),
                            ("EXPIRED", "Expired"),
                            ("FAILED", "Failed"),
                            ("REVERSED", "Reversed"),
                        ],
                        default="STK_PUSH_INITIATED",
                        max_length=30,
                    ),
                ),
                (
                    "checkout_request_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "mpesa_receipt_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, unique=True
                    ),
                ),
                (
                    "merchant_request_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("initiated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
            ],
            options={
                "db_table": "payment_mpesatransaction",
            },
        ),
        migrations.AddIndex(
            model_name="mpesatransaction",
            index=models.Index(
                fields=["store", "reference"],
                name="payment_mpesa_store_ref_idx",
            ),
        ),
    ]
