# Generated by Django 5.2.17 on 2026-09-02 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_card_transaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cardtransaction",
            name="_safedelete_policy",
        ),
        migrations.RemoveField(
            model_name="cardtransaction",
            name="created",
        ),
        migrations.RemoveField(
            model_name="cardtransaction",
            name="updated",
        ),
        migrations.AddField(
            model_name="cardtransaction",
            name="deleted",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="cardtransaction",
            name="deleted_by_cascade",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
