# Generated by Django 5.2.17 on 2026-09-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0004_remove_cardtransaction__safedelete_policy_and_more"),
        ("store", "0009_store_idx_store_status"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="mpesatransaction",
            index=models.Index(
                fields=["checkout_request_id"], name="payment_mpesa_checkout_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mpesatransaction",
            index=models.Index(
                fields=["store", "status"], name="payment_mpesa_store_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mpesatransaction",
            index=models.Index(
                fields=["store", "initiated_at"], name="payment_mpesa_store_date_idx"
            ),
        ),
    ]
