default_context:
  project_name: "joat_stores"
  project_slug: "joat_stores"
  description: "Multi-tenant SaaS e-commerce for Kenyan SMEs"
  author_name: "KAFURAHA"
  email: "kafuraha@joat.com"
  domain_name: "joat.com"
  version: "0.1.0"
  open_source_license: "Not open source"
  username_type: "email"
  timezone: "Africa/Nairobi"
  windows: "n"
  editor: "None"
  use_docker: "y"
  postgresql_version: "17"
  cloud_provider: "None"
  mail_service: "Other SMTP"
  use_async: "n"
  use_drf: "y"
  api_client: "None"
  frontend_pipeline: "None"
  use_celery: "y"
  use_mailpit: "y"
  use_sentry: "y"
  use_whitenoise: "y"
  use_heroku: "n"
  ci_tool: "Github"
  keep_local_envs_in_vcs: "n"
  debug: "y"
