# Generated by Django 5.2.17 on 2026-09-02 00:07
# Updated: Removed AlterField id operations (id is already UUIDField from 0001).

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_fcm_device_model"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="whatsappmessage",
            name="idx_notif_wa_store_queued",
        ),
        migrations.AddField(
            model_name="whatsappinboundmessage",
            name="deleted",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="whatsappinboundmessage",
            name="deleted_by_cascade",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="whatsappmessage",
            name="deleted",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="whatsappmessage",
            name="deleted_by_cascade",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
