"""
Pre-built theme presets for StoreTheme.

Each preset is a dict of field → value that gets written to the store's
StoreTheme record via apply_preset().

Phase 1 — 5 presets: modern, classic, minimal, bold, vibrant.
"""

from decimal import Decimal

PRESETS = {
    "modern": {
        "preset_slug": "modern",
        "template_style": "modern",
        # Colours
        "primary_color": "#1a1a1a",
        "secondary_color": "#6b7280",
        "accent_color": "#e63946",
        "background_color": "#ffffff",
        "surface_color": "#f9fafb",
        "text_primary_color": "#111827",
        "text_secondary_color": "#6b7280",
        "success_color": "#16a34a",
        "error_color": "#dc2626",
        "warning_color": "#f59e0b",
        "header_background": "#1a1a1a",
        "header_text_color": "#ffffff",
        "footer_background": "#1f2937",
        "footer_text_color": "#f3f4f6",
        # Typography
        "font_family_heading": "Inter",
        "font_family_body": "Inter",
        "font_size_base": "1rem",
        "font_size_scale": Decimal("1.250"),
        # Spacing
        "section_padding_y": "4rem",
        "card_padding": "1.5rem",
        "container_max_width": "1280px",
        # Radius
        "radius_sm": "0.25rem",
        "radius_md": "0.5rem",
        "radius_lg": "0.75rem",
        "radius_full": "9999px",
        # Shadows
        "shadow_sm": "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        "shadow_md": "0 4px 6px -1px rgb(0 0 0 / 0.1)",
        "shadow_lg": "0 10px 15px -3px rgb(0 0 0 / 0.1)",
        # Announcement
        "announcement_enabled": False,
        "announcement_text": "",
        "custom_css": "",
    },
    "classic": {
        "preset_slug": "classic",
        "template_style": "classic",
        "primary_color": "#2c3e50",
        "secondary_color": "#95a5a6",
        "accent_color": "#c0392b",
        "background_color": "#fdfcf8",
        "surface_color": "#ffffff",
        "text_primary_color": "#2c3e50",
        "text_secondary_color": "#7f8c8d",
        "success_color": "#27ae60",
        "error_color": "#c0392b",
        "warning_color": "#f39c12",
        "header_background": "#2c3e50",
        "header_text_color": "#ecf0f1",
        "footer_background": "#2c3e50",
        "footer_text_color": "#bdc3c7",
        "font_family_heading": "Merriweather",
        "font_family_body": "Lora",
        "font_size_base": "1.125rem",
        "font_size_scale": Decimal("1.200"),
        "section_padding_y": "5rem",
        "card_padding": "2rem",
        "container_max_width": "1200px",
        "radius_sm": "0",
        "radius_md": "0",
        "radius_lg": "0",
        "radius_full": "0",
        "shadow_sm": "0 1px 3px 0 rgb(0 0 0 / 0.08)",
        "shadow_md": "0 4px 12px 0 rgb(0 0 0 / 0.06)",
        "shadow_lg": "0 8px 24px 0 rgb(0 0 0 / 0.08)",
        "announcement_enabled": False,
        "announcement_text": "",
        "custom_css": "",
    },
    "minimal": {
        "preset_slug": "minimal",
        "template_style": "minimal",
        "primary_color": "#000000",
        "secondary_color": "#737373",
        "accent_color": "#2563eb",
        "background_color": "#fafafa",
        "surface_color": "#ffffff",
        "text_primary_color": "#0a0a0a",
        "text_secondary_color": "#737373",
        "success_color": "#059669",
        "error_color": "#dc2626",
        "warning_color": "#d97706",
        "header_background": "#ffffff",
        "header_text_color": "#0a0a0a",
        "footer_background": "#fafafa",
        "footer_text_color": "#525252",
        "font_family_heading": "Inter",
        "font_family_body": "Inter",
        "font_size_base": "1rem",
        "font_size_scale": Decimal("1.125"),
        "section_padding_y": "6rem",
        "card_padding": "1rem",
        "container_max_width": "1120px",
        "radius_sm": "0.125rem",
        "radius_md": "0.25rem",
        "radius_lg": "0.375rem",
        "radius_full": "9999px",
        "shadow_sm": "0 1px 2px 0 rgb(0 0 0 / 0.03)",
        "shadow_md": "0 1px 3px 0 rgb(0 0 0 / 0.06)",
        "shadow_lg": "0 4px 6px 0 rgb(0 0 0 / 0.04)",
        "announcement_enabled": False,
        "announcement_text": "",
        "custom_css": "",
    },
    "bold": {
        "preset_slug": "bold",
        "template_style": "bold",
        "primary_color": "#7c3aed",
        "secondary_color": "#a78bfa",
        "accent_color": "#f59e0b",
        "background_color": "#0f0f1a",
        "surface_color": "#1a1a2e",
        "text_primary_color": "#f3f4f6",
        "text_secondary_color": "#9ca3af",
        "success_color": "#10b981",
        "error_color": "#ef4444",
        "warning_color": "#f59e0b",
        "header_background": "#0f0f1a",
        "header_text_color": "#f3f4f6",
        "footer_background": "#0f0f1a",
        "footer_text_color": "#9ca3af",
        "font_family_heading": "Space Grotesk",
        "font_family_body": "Inter",
        "font_size_base": "1rem",
        "font_size_scale": Decimal("1.333"),
        "section_padding_y": "5rem",
        "card_padding": "2rem",
        "container_max_width": "1280px",
        "radius_sm": "0.375rem",
        "radius_md": "0.75rem",
        "radius_lg": "1rem",
        "radius_full": "9999px",
        "shadow_sm": "0 1px 3px 0 rgb(124 58 237 / 0.2)",
        "shadow_md": "0 4px 12px 0 rgb(124 58 237 / 0.15)",
        "shadow_lg": "0 8px 32px 0 rgb(124 58 237 / 0.2)",
        "announcement_enabled": False,
        "announcement_text": "",
        "custom_css": "",
    },
    "vibrant": {
        "preset_slug": "vibrant",
        "template_style": "modern",
        "primary_color": "#0891b2",
        "secondary_color": "#06b6d4",
        "accent_color": "#f97316",
        "background_color": "#ffffff",
        "surface_color": "#ecfeff",
        "text_primary_color": "#164e63",
        "text_secondary_color": "#64748b",
        "success_color": "#10b981",
        "error_color": "#ef4444",
        "warning_color": "#f59e0b",
        "header_background": "#0891b2",
        "header_text_color": "#ffffff",
        "footer_background": "#164e63",
        "footer_text_color": "#cffafe",
        "font_family_heading": "Poppins",
        "font_family_body": "Inter",
        "font_size_base": "1rem",
        "font_size_scale": Decimal("1.250"),
        "section_padding_y": "4rem",
        "card_padding": "1.5rem",
        "container_max_width": "1280px",
        "radius_sm": "0.375rem",
        "radius_md": "0.75rem",
        "radius_lg": "1.25rem",
        "radius_full": "9999px",
        "shadow_sm": "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        "shadow_md": "0 4px 12px 0 rgb(8 145 178 / 0.12)",
        "shadow_lg": "0 12px 24px -4px rgb(8 145 178 / 0.15)",
        "announcement_enabled": False,
        "announcement_text": "",
        "custom_css": "",
    },
}


def apply_preset(theme, preset_slug):
    """Write every field from the preset onto a StoreTheme instance and save.

    Returns the updated instance.
    """
    data = PRESETS.get(preset_slug)
    if data is None:
        raise ValueError(f"Unknown preset: {preset_slug}")

    for field, value in data.items():
        setattr(theme, field, value)
    theme.save()
    return theme
