# Generated by Django 5.2.3 on 2026-03-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("store", "0002_uuid_pk_tenant_models"),
        ("users", "0001_add_store_fk_unique_email_store"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("store__isnull", True)),
                fields=("email",),
                name="uq_platform_admin_email",
            ),
        ),
    ]
