# Generated by Django 5.2.3 on 2026-06-23 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_uq_platform_admin_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=30, null=True, unique=True),
                ),
                ("full_name", models.CharField(blank=True, default="", max_length=255)),
                ("avatar_url", models.URLField(blank=True, default="")),
                (
                    "google_sub",
                    models.CharField(
                        blank=True,
                        help_text="Google OAuth subject ID for cross-store identity linking.",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Platform User",
                "verbose_name_plural": "Platform Users",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="platform_user",
            field=models.ForeignKey(
                blank=True,
                help_text="Links this store-scoped user to their global identity.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="store_users",
                to="users.platformuser",
            ),
        ),
    ]
