# Generated by Django 5.2.17 on 2026-09-03 20:28

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("store", "0009_store_idx_store_status"),
        ("users", "0003_platform_user_model"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.users.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("platform_admin", "Platform Admin"),
                    ("store_owner", "Store Owner"),
                    ("store_manager", "Store Manager"),
                    ("cashier", "Cashier"),
                    ("waiter", "Waiter"),
                    ("kitchen", "Kitchen Staff"),
                    ("customer", "Customer"),
                ],
                default="customer",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["store", "role"], name="idx_user_store_role"),
        ),
    ]
