# Generated by Django 5.2.17 on 2026-09-02 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracting", "0001_contracting_initial"),
        ("store", "0006_remove_storetheme_font_family_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="availabilityslot",
            new_name="ct_slot_service_time",
            old_name="idx_contracting_slot_service_time",
        ),
        migrations.RenameIndex(
            model_name="invoice",
            new_name="ct_invoice_payment",
            old_name="idx_contracting_invoice_payment",
        ),
        migrations.RenameIndex(
            model_name="quoterequest",
            new_name="ct_quotereq_status",
            old_name="idx_contracting_quotereq_status",
        ),
        migrations.RenameIndex(
            model_name="servicebooking",
            new_name="ct_booking_status",
            old_name="idx_contracting_booking_status",
        ),
        migrations.AlterField(
            model_name="availabilityslot",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="store.store",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="line_items",
            field=models.JSONField(
                help_text="List of {description, quantity, unit_price} dicts."
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="store.store",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="store.store",
            ),
        ),
        migrations.AlterField(
            model_name="jobmilestone",
            name="completion_photo",
            field=models.ImageField(
                blank=True,
                help_text="Compressed to WebP ≤ 800 KB before saving.",
                null=True,
                upload_to="contracting/milestones/",
            ),
        ),
        migrations.AlterField(
            model_name="jobmilestone",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="store.store",
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="line_items",
            field=models.JSONField(
                help_text="List of {description, quantity, unit_price} dicts."
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="store.store",
            ),
        ),
        migrations.AlterField(
            model_name="quoterequest",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="store.store",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="duration_estimate",
            field=models.PositiveIntegerField(
                help_text="Estimated duration in minutes."
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="store.store",
            ),
        ),
        migrations.AlterField(
            model_name="servicebooking",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="store.store",
            ),
        ),
    ]
