# Generated by Django 5.2.17 on 2026-09-02 00:07

import django.db.models.deletion
from django.db import migrations, models


def _index_exists(cursor, name):
    cursor.execute("SELECT 1 FROM pg_indexes WHERE indexname = %s", [name])
    return cursor.fetchone() is not None


INDEX_RENAMES = [
    ("availabilityslot", "idx_contracting_slot_service_time", "ct_slot_service_time"),
    ("invoice", "idx_contracting_invoice_payment", "ct_invoice_payment"),
    ("quoterequest", "idx_contracting_quotereq_status", "ct_quotereq_status"),
    ("servicebooking", "idx_contracting_booking_status", "ct_booking_status"),
]


def safe_contracting_forward(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        for table, old_name, new_name in INDEX_RENAMES:
            if _index_exists(cursor, old_name) and not _index_exists(cursor, new_name):
                schema_editor.execute(f'ALTER INDEX "{old_name}" RENAME TO "{new_name}"')
            elif not _index_exists(cursor, old_name) and not _index_exists(cursor, new_name):
                # Index doesn't exist under either name — skip silently
                pass


def safe_contracting_backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("contracting", "0001_contracting_initial"),
        ("store", "0006_remove_storetheme_font_family_and_more"),
    ]

    operations = [
        migrations.RunPython(safe_contracting_forward, safe_contracting_backward),
        migrations.AlterField(
            model_name="availabilityslot",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="store.store",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="line_items",
            field=models.JSONField(
                help_text="List of {description, quantity, unit_price} dicts."
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="store.store",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="store.store",
            ),
        ),
        migrations.AlterField(
            model_name="jobmilestone",
            name="completion_photo",
            field=models.ImageField(
                blank=True,
                help_text="Compressed to WebP ≤ 800 KB before saving.",
                null=True,
                upload_to="contracting/milestones/",
            ),
        ),
        migrations.AlterField(
            model_name="jobmilestone",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="store.store",
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="line_items",
            field=models.JSONField(
                help_text="List of {description, quantity, unit_price} dicts."
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="store.store",
            ),
        ),
        migrations.AlterField(
            model_name="quoterequest",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="store.store",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="duration_estimate",
            field=models.PositiveIntegerField(
                help_text="Estimated duration in minutes."
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="store.store",
            ),
        ),
        migrations.AlterField(
            model_name="servicebooking",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="store.store",
            ),
        ),
    ]
