# Generated by Django 5.2.17 on 2026-09-03 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "contracting",
            "0002_rename_idx_contracting_slot_service_time_ct_slot_service_time_and_more",
        ),
    ]

    operations = []
