# Generated by Django 5.2.3 on 2026-09-06 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "contracting",
            "0003_rename_idx_contracting_slot_service_time_ct_slot_service_time_and_more",
        ),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="availabilityslot",
            new_name="ct_slot_service_time",
            old_name="idx_contracting_slot_service_time",
        ),
        migrations.RenameIndex(
            model_name="invoice",
            new_name="ct_invoice_payment",
            old_name="idx_contracting_invoice_payment",
        ),
        migrations.RenameIndex(
            model_name="quoterequest",
            new_name="ct_quotereq_status",
            old_name="idx_contracting_quotereq_status",
        ),
        migrations.RenameIndex(
            model_name="servicebooking",
            new_name="ct_booking_status",
            old_name="idx_contracting_booking_status",
        ),
    ]
