# Generated by Django 5.2.3 on 2026-03-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_uuid_pk_tenant_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="storesettings",
            name="logo_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Absolute URL to the store's WebP logo.",
            ),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="tagline",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Short store tagline shown on the storefront.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="storetheme",
            name="font_family",
            field=models.CharField(
                default="Inter",
                help_text="Font family name (e.g. 'Inter', 'Roboto').",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="storetheme",
            name="primary_color",
            field=models.CharField(
                default="#1a1a1a",
                help_text="CSS colour value for brand primary (e.g. #e63946).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="storetheme",
            name="secondary_color",
            field=models.CharField(
                default="#6b7280",
                help_text="CSS colour value for brand secondary.",
                max_length=20,
            ),
        ),
    ]
