# Generated by Django 5.2.3 on 2026-03-13 22:12

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_storesettings_storetheme_branding_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storetheme",
            name="primary_color",
            field=models.CharField(
                default="#1a1a1a",
                help_text="CSS colour value for brand primary (e.g. #e63946).",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid CSS colour value (hex, rgb(), or named colour).",
                        regex=re.compile(
                            "^(#([0-9a-fA-F]{3}){1,2}|rgb\\(\\d{1,3},\\s*\\d{1,3},\\s*\\d{1,3}\\)|[a-zA-Z]+)$"
                        ),
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="storetheme",
            name="secondary_color",
            field=models.CharField(
                default="#6b7280",
                help_text="CSS colour value for brand secondary.",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid CSS colour value (hex, rgb(), or named colour).",
                        regex=re.compile(
                            "^(#([0-9a-fA-F]{3}){1,2}|rgb\\(\\d{1,3},\\s*\\d{1,3},\\s*\\d{1,3}\\)|[a-zA-Z]+)$"
                        ),
                    )
                ],
            ),
        ),
    ]
