# Generated by Django 5.2.3 on 2026-06-19 15:32

import django.core.validators
import re
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_storesettings_low_stock_threshold"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storetheme",
            name="font_family",
        ),
        migrations.AddField(
            model_name="storetheme",
            name="accent_color",
            field=models.CharField(
                default="#e63946",
                help_text="Highlights, CTAs, sale badges.",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid CSS colour value (hex, rgb(), or named colour).",
                        regex=re.compile(
                            "^(#([0-9a-fA-F]{3}){1,2}|rgb\\(\\d{1,3},\\s*\\d{1,3},\\s*\\d{1,3}\\)|[a-zA-Z]+)$"
                        ),
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="storetheme",
            name="announcement_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="storetheme",
            name="announcement_text",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="storetheme",
            name="background_color",
            field=models.CharField(
                default="#ffffff",
                help_text="Page background.",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid CSS colour value (hex, rgb(), or named colour).",
                        regex=re.compile(
                            "^(#([0-9a-fA-F]{3}){1,2}|rgb\\(\\d{1,3},\\s*\\d{1,3},\\s*\\d{1,3}\\)|[a-zA-Z]+)$"
                        ),
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="storetheme",
            name="card_padding",
            field=models.CharField(
                default="1.5rem", help_text="Inner card padding.", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="storetheme",
            name="container_max_width",
            field=models.CharField(
                default="1280px", help_text="Max page width.", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="storetheme",
            name="custom_css",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Raw CSS injected via <style> tag. Overrides any token above.",
            ),
        ),
        migrations.AddField(
            model_name="storetheme",
            name="error_color",
            field=models.CharField(
                default="#dc2626",
                help_text="Error / out-of-stock indicator.",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid CSS colour value (hex, rgb(), or named colour).",
                        regex=re.compile(
                            "^(#([0-9a-fA-F]{3}){1,2}|rgb\\(\\d{1,3},\\s*\\d{1,3},\\s*\\d{1,3}\\)|[a-zA-Z]+)$"
                        ),
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="storetheme",
            name="font_family_body",
            field=models.CharField(
                default="Inter", help_text="Body font family.", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="storetheme",
            name="font_family_heading",
            field=models.CharField(
                default="Inter", help_text="Heading font family.", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="storetheme",
            name="font_size_base",
            field=models.CharField(
                default="1rem",
                help_text="Base font size (e.g. 1rem, 16px).",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="storetheme",
            name="font_size_scale",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.250"),
                help_text="Heading scale factor (1.250 = Major Third).",
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="storetheme",
            name="footer_background",
            field=models.CharField(
                default="#1f2937",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid CSS colour value (hex, rgb(), or named colour).",
                        regex=re.compile(
                            "^(#([0-9a-fA-F]{3}){1,2}|rgb\\(\\d{1,3},\\s*\\d{1,3},\\s*\\d{1,3}\\)|[a-zA-Z]+)$"
                        ),
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="storetheme",
            name="footer_text_color",
            field=models.CharField(
                default="#f3f4f6",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid CSS colour value (hex, rgb(), or named colour).",
                        regex=re.compile(
                            "^(#([0-9a-fA-F]{3}){1,2}|rgb\\(\\d{1,3},\\s*\\d{1,3},\\s*\\d{1,3}\\)|[a-zA-Z]+)$"
                        ),
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="storetheme",
            name="header_background",
            field=models.CharField(
                default="#1a1a1a",
                help_text="Header bar background.",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid CSS colour value (hex, rgb(), or named colour).",
                        regex=re.compile(
                            "^(#([0-9a-fA-F]{3}){1,2}|rgb\\(\\d{1,3},\\s*\\d{1,3},\\s*\\d{1,3}\\)|[a-zA-Z]+)$"
                        ),
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="storetheme",
            name="header_text_color",
            field=models.CharField(
                default="#ffffff",
                help_text="Header text / link colour.",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid CSS colour value (hex, rgb(), or named colour).",
                        regex=re.compile(
                            "^(#([0-9a-fA-F]{3}){1,2}|rgb\\(\\d{1,3},\\s*\\d{1,3},\\s*\\d{1,3}\\)|[a-zA-Z]+)$"
                        ),
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="storetheme",
            name="preset_slug",
            field=models.CharField(
                default="modern",
                help_text="Slug of the last-applied preset (modern|classic|minimal|bold|vibrant).",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="storetheme",
            name="radius_full",
            field=models.CharField(default="9999px", max_length=10),
        ),
        migrations.AddField(
            model_name="storetheme",
            name="radius_lg",
            field=models.CharField(default="0.75rem", max_length=10),
        ),
        migrations.AddField(
            model_name="storetheme",
            name="radius_md",
            field=models.CharField(default="0.5rem", max_length=10),
        ),
        migrations.AddField(
            model_name="storetheme",
            name="radius_sm",
            field=models.CharField(default="0.25rem", max_length=10),
        ),
        migrations.AddField(
            model_name="storetheme",
            name="section_padding_y",
            field=models.CharField(
                default="4rem",
                help_text="Vertical section padding (e.g. 4rem, 64px).",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="storetheme",
            name="shadow_lg",
            field=models.CharField(
                default="0 10px 15px -3px rgb(0 0 0 / 0.1)", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="storetheme",
            name="shadow_md",
            field=models.CharField(
                default="0 4px 6px -1px rgb(0 0 0 / 0.1)", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="storetheme",
            name="shadow_sm",
            field=models.CharField(
                default="0 1px 2px 0 rgb(0 0 0 / 0.05)", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="storetheme",
            name="success_color",
            field=models.CharField(
                default="#16a34a",
                help_text="Success / in-stock indicator.",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid CSS colour value (hex, rgb(), or named colour).",
                        regex=re.compile(
                            "^(#([0-9a-fA-F]{3}){1,2}|rgb\\(\\d{1,3},\\s*\\d{1,3},\\s*\\d{1,3}\\)|[a-zA-Z]+)$"
                        ),
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="storetheme",
            name="surface_color",
            field=models.CharField(
                default="#f9fafb",
                help_text="Card / section background.",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid CSS colour value (hex, rgb(), or named colour).",
                        regex=re.compile(
                            "^(#([0-9a-fA-F]{3}){1,2}|rgb\\(\\d{1,3},\\s*\\d{1,3},\\s*\\d{1,3}\\)|[a-zA-Z]+)$"
                        ),
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="storetheme",
            name="template_style",
            field=models.CharField(
                default="modern",
                help_text="Layout variant key (modern|classic|minimal|bold).",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="storetheme",
            name="text_primary_color",
            field=models.CharField(
                default="#111827",
                help_text="Primary text colour.",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid CSS colour value (hex, rgb(), or named colour).",
                        regex=re.compile(
                            "^(#([0-9a-fA-F]{3}){1,2}|rgb\\(\\d{1,3},\\s*\\d{1,3},\\s*\\d{1,3}\\)|[a-zA-Z]+)$"
                        ),
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="storetheme",
            name="text_secondary_color",
            field=models.CharField(
                default="#6b7280",
                help_text="Secondary / muted text colour.",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid CSS colour value (hex, rgb(), or named colour).",
                        regex=re.compile(
                            "^(#([0-9a-fA-F]{3}){1,2}|rgb\\(\\d{1,3},\\s*\\d{1,3},\\s*\\d{1,3}\\)|[a-zA-Z]+)$"
                        ),
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="storetheme",
            name="warning_color",
            field=models.CharField(
                default="#f59e0b",
                help_text="Warning / low-stock indicator.",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid CSS colour value (hex, rgb(), or named colour).",
                        regex=re.compile(
                            "^(#([0-9a-fA-F]{3}){1,2}|rgb\\(\\d{1,3},\\s*\\d{1,3},\\s*\\d{1,3}\\)|[a-zA-Z]+)$"
                        ),
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="storetheme",
            name="primary_color",
            field=models.CharField(
                default="#1a1a1a",
                help_text="Brand primary — nav bg, buttons, links.",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid CSS colour value (hex, rgb(), or named colour).",
                        regex=re.compile(
                            "^(#([0-9a-fA-F]{3}){1,2}|rgb\\(\\d{1,3},\\s*\\d{1,3},\\s*\\d{1,3}\\)|[a-zA-Z]+)$"
                        ),
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="storetheme",
            name="secondary_color",
            field=models.CharField(
                default="#6b7280",
                help_text="Brand secondary — muted accents, borders.",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid CSS colour value (hex, rgb(), or named colour).",
                        regex=re.compile(
                            "^(#([0-9a-fA-F]{3}){1,2}|rgb\\(\\d{1,3},\\s*\\d{1,3},\\s*\\d{1,3}\\)|[a-zA-Z]+)$"
                        ),
                    )
                ],
            ),
        ),
    ]
