# Generated by Django 5.2.3 on 2026-09-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_remove_storetheme_font_family_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="storesettings",
            name="currency_symbol",
            field=models.CharField(
                default="KES",
                help_text="Currency symbol displayed in the admin and storefront.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="receipt_footer",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Text shown at the bottom of receipts.",
            ),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="receipt_header",
            field=models.TextField(
                blank=True, default="", help_text="Text shown at the top of receipts."
            ),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="tax_inclusive",
            field=models.BooleanField(
                default=True,
                help_text="If True, prices include tax. If False, tax is added on top.",
            ),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=0.16,
                help_text="Tax rate as decimal (e.g., 0.1600 for 16% VAT).",
                max_digits=5,
            ),
        ),
    ]
