# Generated by Django 5.2.17 on 2026-09-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_add_store_settings_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="mpesa_shortcode",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Safaricom till/paybill number for C2B customer-initiated payments.",
                max_length=20,
            ),
        ),
    ]
