# Generated by Django 5.2.17 on 2026-09-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_add_mpesa_shortcode"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="store",
            index=models.Index(fields=["status"], name="idx_store_status"),
        ),
    ]
