# Generated by Django 5.2.3 on 2026-03-13 22:12

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("store", "0004_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuSection",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "position",
                    models.PositiveSmallIntegerField(db_index=True, default=0),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="store.store",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "name"],
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator("0.00")],
                    ),
                ),
                ("contains_allergens", models.BooleanField(default=False)),
                ("allergen_description", models.TextField(blank=True, default="")),
                ("is_available", models.BooleanField(default=True)),
                (
                    "available_from",
                    models.TimeField(
                        blank=True,
                        help_text="Start time for availability window (e.g. 06:00). Null = always.",
                        null=True,
                    ),
                ),
                (
                    "available_until",
                    models.TimeField(
                        blank=True,
                        help_text="End time for availability window (e.g. 11:00). Null = always.",
                        null=True,
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="store.store",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="restaurant.menusection",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "name"],
            },
        ),
        migrations.CreateModel(
            name="ModifierGroup",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "min_selections",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Minimum number of modifiers the customer must choose.",
                    ),
                ),
                (
                    "max_selections",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Maximum number of modifiers the customer may choose.",
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modifier_groups",
                        to="restaurant.menuitem",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="store.store",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Modifier",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "price_addition",
                    models.DecimalField(
                        decimal_places=2,
                        default="0.00",
                        help_text="Additional cost when this modifier is selected.",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator("0.00")],
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="store.store",
                    ),
                ),
                (
                    "modifier_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modifiers",
                        to="restaurant.modifiergroup",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddIndex(
            model_name="menusection",
            index=models.Index(
                fields=["store", "position"], name="idx_rst_msection_store_pos"
            ),
        ),
        migrations.AddConstraint(
            model_name="menusection",
            constraint=models.UniqueConstraint(
                fields=("store", "name"), name="uq_restaurant_menusection_store_name"
            ),
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(
                fields=["store", "section"], name="idx_rst_mitem_store_section"
            ),
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(
                fields=["store", "is_available"], name="idx_rst_mitem_store_avail"
            ),
        ),
        migrations.AddIndex(
            model_name="modifiergroup",
            index=models.Index(
                fields=["store", "menu_item"], name="idx_rst_modgrp_store_item"
            ),
        ),
        migrations.AddIndex(
            model_name="modifier",
            index=models.Index(
                fields=["store", "modifier_group"], name="idx_rst_modifier_store_grp"
            ),
        ),
    ]
