# Generated by Django 5.2.3 on 2026-03-14 04:56

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
        ("store", "0004_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="modifier",
            name="price_addition",
            field=models.DecimalField(
                decimal_places=2,
                default="0.00",
                help_text="Additional cost when this modifier is selected.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        help_text="Table number visible to staff/customers."
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional friendly name (e.g. 'Window Table').",
                        max_length=50,
                    ),
                ),
                ("capacity", models.PositiveSmallIntegerField(default=2)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="store.store",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
                "indexes": [
                    models.Index(
                        fields=["store", "is_active"], name="idx_rst_table_store_active"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("store", "number"),
                        name="uq_restaurant_table_store_number",
                    )
                ],
            },
        ),
    ]
