# Generated by Django 5.2.17 on 2026-09-02 00:07

import apps.restaurant.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0011_menuitem_is_age_restricted"),
        ("store", "0006_remove_storetheme_font_family_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="menusection",
            name="uq_restaurant_menusection_store_name",
        ),
        migrations.RemoveConstraint(
            model_name="table",
            name="uq_restaurant_table_store_number",
        ),
        migrations.RemoveConstraint(
            model_name="tablesession",
            name="uq_restaurant_tablesession_one_open_per_table",
        ),
        migrations.RenameIndex(
            model_name="billshare",
            new_name="rst_blshr_session_status",
            old_name="idx_rst_billshare_session_status",
        ),
        migrations.RenameIndex(
            model_name="dineinorder",
            new_name="rst_dinord_store_status",
            old_name="idx_rst_dineinorder_store_status",
        ),
        migrations.RenameIndex(
            model_name="kitchenticket",
            new_name="rst_kittkt_store_status",
            old_name="idx_rst_kitchenticket_store_status",
        ),
        migrations.RenameIndex(
            model_name="pendingorder",
            new_name="rst_porder_store_status",
            old_name="idx_rst_pendingorder_store_status",
        ),
        migrations.RenameIndex(
            model_name="pendingorder",
            new_name="rst_porder_store_pin_status",
            old_name="idx_rst_pendingorder_store_pin_status",
        ),
        migrations.RenameIndex(
            model_name="pendingorder",
            new_name="rst_porder_store_phone_status",
            old_name="idx_rst_pendingorder_store_phone_status",
        ),
        migrations.RenameIndex(
            model_name="reservation",
            new_name="rst_reserv_store_status",
            old_name="idx_rst_reservation_store_status",
        ),
        migrations.RenameIndex(
            model_name="reservation",
            new_name="rst_reserv_store_time",
            old_name="idx_rst_reservation_store_time",
        ),
        migrations.RenameIndex(
            model_name="tablesession",
            new_name="rst_tsess_store_status",
            old_name="idx_rst_tablesession_store_status",
        ),
        migrations.RenameIndex(
            model_name="tablesession",
            new_name="rst_tsess_table_status",
            old_name="idx_rst_tablesession_table_status",
        ),
        migrations.AlterField(
            model_name="billshare",
            name="items_snapshot",
            field=models.JSONField(
                default=list,
                help_text="Denormalized list of items in this payer's share.",
            ),
        ),
        migrations.AlterField(
            model_name="dineinorder",
            name="items_snapshot",
            field=models.JSONField(
                help_text="Denormalized list of ordered items captured at creation time."
            ),
        ),
        migrations.AlterField(
            model_name="kitchenticket",
            name="items_snapshot",
            field=models.JSONField(
                help_text="Copy of DineInOrder.items_snapshot at ticket creation time."
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="is_age_restricted",
            field=models.BooleanField(
                default=False,
                help_text="If True, customers must acknowledge 18+ age restriction in bar tabs.",
            ),
        ),
        migrations.AlterField(
            model_name="pendingorder",
            name="expires_at",
            field=models.DateTimeField(
                help_text="24h from creation — after this the order is purged by Celery beat."
            ),
        ),
        migrations.AlterField(
            model_name="pendingorder",
            name="items_snapshot",
            field=models.JSONField(
                help_text="Denormalized list of ordered items captured at creation time."
            ),
        ),
        migrations.AlterField(
            model_name="pendingorder",
            name="phone",
            field=models.CharField(
                help_text="Customer phone number in E.164 format.", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="pendingorder",
            name="pin",
            field=models.CharField(
                default=apps.restaurant.models._generate_pin,
                help_text="6-digit PIN the customer gives the waiter on arrival.",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reserved_for",
            field=models.DateTimeField(
                help_text="Requested time slot for the reservation."
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="table",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific table reserved. May be assigned at confirmation.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservations",
                to="restaurant.table",
            ),
        ),
        migrations.AddConstraint(
            model_name="menusection",
            constraint=models.UniqueConstraint(
                fields=("store", "name"), name="rst_msection_store_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="table",
            constraint=models.UniqueConstraint(
                fields=("store", "number"), name="rst_table_store_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="tablesession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "OPEN")),
                fields=("table",),
                name="rst_tsess_one_open",
            ),
        ),
    ]
