# Generated by Django 5.2.17 on 2026-09-03 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "restaurant",
            "0012_remove_menusection_uq_restaurant_menusection_store_name_and_more",
        ),
    ]

    operations = []
