# Generated by Django 5.2.3 on 2026-09-06 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "restaurant",
            "0013_remove_menusection_uq_restaurant_menusection_store_name_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="menusection",
            name="uq_restaurant_menusection_store_name",
        ),
        migrations.RemoveConstraint(
            model_name="table",
            name="uq_restaurant_table_store_number",
        ),
        migrations.RemoveConstraint(
            model_name="tablesession",
            name="uq_restaurant_tablesession_one_open_per_table",
        ),
        migrations.RenameIndex(
            model_name="billshare",
            new_name="rst_blshr_session_status",
            old_name="idx_rst_billshare_session_status",
        ),
        migrations.RenameIndex(
            model_name="dineinorder",
            new_name="rst_dinord_store_status",
            old_name="idx_rst_dineinorder_store_status",
        ),
        migrations.RenameIndex(
            model_name="kitchenticket",
            new_name="rst_kittkt_store_status",
            old_name="idx_rst_kitchenticket_store_status",
        ),
        migrations.RenameIndex(
            model_name="pendingorder",
            new_name="rst_porder_store_status",
            old_name="idx_rst_pendingorder_store_status",
        ),
        migrations.RenameIndex(
            model_name="pendingorder",
            new_name="rst_porder_store_pin_status",
            old_name="idx_rst_pendingorder_store_pin_status",
        ),
        migrations.RenameIndex(
            model_name="pendingorder",
            new_name="rst_porder_store_phone_status",
            old_name="idx_rst_pendingorder_store_phone_status",
        ),
        migrations.RenameIndex(
            model_name="reservation",
            new_name="rst_reserv_store_status",
            old_name="idx_rst_reservation_store_status",
        ),
        migrations.RenameIndex(
            model_name="reservation",
            new_name="rst_reserv_store_time",
            old_name="idx_rst_reservation_store_time",
        ),
        migrations.RenameIndex(
            model_name="tablesession",
            new_name="rst_tsess_store_status",
            old_name="idx_rst_tablesession_store_status",
        ),
        migrations.RenameIndex(
            model_name="tablesession",
            new_name="rst_tsess_table_status",
            old_name="idx_rst_tablesession_table_status",
        ),
    ]
