# Generated by Django 5.2.17 on 2026-09-02 00:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def _index_exists(cursor, name):
    cursor.execute("SELECT 1 FROM pg_indexes WHERE indexname = %s", [name])
    return cursor.fetchone() is not None


def _constraint_exists(cursor, table, name):
    cursor.execute(
        "SELECT 1 FROM information_schema.table_constraints "
        "WHERE table_name = %s AND constraint_name = %s",
        [table, name],
    )
    return cursor.fetchone() is not None


def safe_bar_forward(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        # RenameIndex: idx_bar_agerestrictionlog_tab_customer → bar_agelog_tab_customer
        old = "idx_bar_agerestrictionlog_tab_customer"
        new = "bar_agelog_tab_customer"
        if _index_exists(cursor, old) and not _index_exists(cursor, new):
            schema_editor.execute(f'ALTER INDEX "{old}" RENAME TO "{new}"')
        elif not _index_exists(cursor, old) and not _index_exists(cursor, new):
            schema_editor.execute(
                f'CREATE INDEX "{new}" ON "bar_agerestrictionlog" ("tab_id", "customer_id")'
            )

        # RemoveConstraint: uq_bar_tabround_tab_round_number (idempotent)
        if _constraint_exists(cursor, "bar_tabround", "uq_bar_tabround_tab_round_number"):
            schema_editor.execute(
                'ALTER TABLE "bar_tabround" DROP CONSTRAINT "uq_bar_tabround_tab_round_number"'
            )


def safe_bar_backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("bar", "0001_bar_initial"),
        ("store", "0006_remove_storetheme_font_family_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(safe_bar_forward, safe_bar_backward),
        migrations.AlterField(
            model_name="agerestrictionlog",
            name="customer_phone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Used when customer is not authenticated.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="agerestrictionlog",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="store.store",
            ),
        ),
        migrations.AlterField(
            model_name="happyhour",
            name="days_of_week",
            field=models.JSONField(
                default=list,
                help_text="ISO weekday list: 0=Monday … 6=Sunday. Empty = every day.",
            ),
        ),
        migrations.AlterField(
            model_name="happyhour",
            name="discount_percent",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Discount percentage applied to all items during this window.",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="happyhour",
            name="end_time",
            field=models.TimeField(help_text="End of happy hour window."),
        ),
        migrations.AlterField(
            model_name="happyhour",
            name="name",
            field=models.CharField(
                help_text="E.g. 'Evening Happy Hour'", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="happyhour",
            name="start_time",
            field=models.TimeField(help_text="Start of happy hour window."),
        ),
        migrations.AlterField(
            model_name="happyhour",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="store.store",
            ),
        ),
        migrations.AlterField(
            model_name="tab",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                help_text="Authenticated customer who opened the tab. Null for walk-in tabs.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bar_tabs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="tab",
            name="customer_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Display name for walk-in customers.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="tab",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="store.store",
            ),
        ),
        migrations.AlterField(
            model_name="tabitem",
            name="is_happy_hour",
            field=models.BooleanField(
                default=False,
                help_text="True if the happy hour discount was applied to unit_price.",
            ),
        ),
        migrations.AlterField(
            model_name="tabitem",
            name="removed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of removal by staff. Null = item is still on tab.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tabitem",
            name="removed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff member who removed this item.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="tabitem",
            name="removed_by_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Denormalized staff name at time of removal.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="tabitem",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="store.store",
            ),
        ),
        migrations.AlterField(
            model_name="tabitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Price snapshotted at add-time (may include happy hour discount).",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="tabround",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="store.store",
            ),
        ),
        migrations.AlterField(
            model_name="tabshare",
            name="item_ids",
            field=models.JSONField(
                default=list,
                help_text="TabItem UUIDs covered by this share. Empty = percentage-based share.",
            ),
        ),
        migrations.AlterField(
            model_name="tabshare",
            name="percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Percentage of total bill (used when item_ids is empty).",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tabshare",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="store.store",
            ),
        ),
        migrations.AddConstraint(
            model_name="tabround",
            constraint=models.UniqueConstraint(
                fields=("tab", "round_number"), name="uq_bar_tabround_number"
            ),
        ),
    ]
