# Generated by Django 5.2.17 on 2026-09-03 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bar", "0002_remove_tabround_uq_bar_tabround_tab_round_number_and_more"),
    ]

    operations = []
