# Generated by Django 5.2.3 on 2026-09-06 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bar", "0003_remove_tabround_uq_bar_tabround_tab_round_number_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="tabround",
            name="uq_bar_tabround_tab_round_number",
        ),
        migrations.RenameIndex(
            model_name="agerestrictionlog",
            new_name="bar_agelog_tab_customer",
            old_name="idx_bar_agerestrictionlog_tab_customer",
        ),
    ]
