# Generated by Django 5.2.17 on 2026-09-02 00:07
# Updated: Removed AlterField id operations (id is already UUIDField from 0001).

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loyalty", "0001_loyalty_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="customerprofile",
            name="idx_loyalty_profile_store_last",
        ),
        migrations.RemoveIndex(
            model_name="pointstransaction",
            name="idx_loyalty_tx_store_date",
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="deleted",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="deleted_by_cascade",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="customerstamp",
            name="deleted",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="customerstamp",
            name="deleted_by_cascade",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="customerstampcard",
            name="deleted",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="customerstampcard",
            name="deleted_by_cascade",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="loyaltyaccount",
            name="deleted",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="loyaltyaccount",
            name="deleted_by_cascade",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="pointstransaction",
            name="deleted",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="pointstransaction",
            name="deleted_by_cascade",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="stampcard",
            name="deleted",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="stampcard",
            name="deleted_by_cascade",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name="loyaltyaccount",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                help_text="Null for guest accounts — linked by customer_phone.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loyalty_accounts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="stampcard",
            name="points_per_stamp",
            field=models.IntegerField(
                default=0,
                help_text="Bonus loyalty points awarded when the card is completed.",
            ),
        ),
    ]
