-- =============================================================================
-- FAKE MIGRATIONS — Run AFTER supabase_seed.sql
-- Tells Django all existing tables were created by migrations
-- =============================================================================

-- Django content types (needed by auth_permission)
INSERT INTO django_content_type (app_label, model) VALUES
('admin', 'logentry'),
('auth', 'permission'),
('auth', 'group'),
('contenttypes', 'contenttype'),
('sessions', 'session'),
('sites', 'site'),
('account', 'emailaddress'),
('account', 'emailconfirmation'),
('socialaccount', 'socialaccount'),
('socialaccount', 'socialapp'),
('socialaccount', 'socialtoken'),
('token_blacklist', 'outstandingtoken'),
('token_blacklist', 'blacklistedtoken'),
('django_celery_beat', 'clockedschedule'),
('django_celery_beat', 'crontabschedule'),
('django_celery_beat', '_intervalschedule'),
('django_celery_beat', 'periodictask'),
('django_celery_beat', 'periodictasks'),
('django_celery_beat', 'solarschedule'),
('users', 'platformuser'),
('users', 'user'),
('store', 'store'),
('store', 'storesettings'),
('store', 'storetheme'),
('saas', 'plan'),
('saas', 'storesubscription'),
('payment', 'mpesatransaction'),
('payment', 'cardtransaction'),
('product', 'category'),
('product', 'product'),
('product', 'variant'),
('product', 'productimage'),
('order', 'order'),
('order', 'cartsnapshot'),
('restaurant', 'menusection'),
('restaurant', 'menuitem'),
('restaurant', 'modifiergroup'),
('restaurant', 'modifier'),
('restaurant', 'table'),
('restaurant', 'tablesession'),
('restaurant', 'dineinorder'),
('restaurant', 'kitchenticket'),
('restaurant', 'pendingorder'),
('restaurant', 'reservation'),
('restaurant', 'billshare'),
('bar', 'tab'),
('bar', 'tabround'),
('bar', 'tabitem'),
('bar', 'happyhour'),
('bar', 'agerestrictionlog'),
('bar', 'tabshare'),
('analytics', 'adminpIIaccesslog'),
('analytics', 'dailyrevenuesummary'),
('analytics', 'hourlyordersummary'),
('notifications', 'whatsappmessage'),
('notifications', 'whatsappinboundmessage'),
('notifications', 'fcmdevice'),
('loyalty', 'loyaltyaccount'),
('loyalty', 'pointstransaction'),
('loyalty', 'stampcard'),
('loyalty', 'customerstampcard'),
('loyalty', 'customerstamp'),
('loyalty', 'customerprofile'),
('contracting', 'service'),
('contracting', 'availabilityslot'),
('contracting', 'servicebooking'),
('contracting', 'quoterequest'),
('contracting', 'quote'),
('contracting', 'job'),
('contracting', 'jobmilestone'),
('contracting', 'invoice')
ON CONFLICT (app_label, model) DO NOTHING;

-- Create auth permissions for each content type
-- We need a function to auto-generate permissions
DO $$
DECLARE
  ct RECORD;
BEGIN
  FOR ct IN SELECT id, app_label, model FROM django_content_type LOOP
    INSERT INTO auth_permission (name, content_type_id, codename) VALUES
      (ct.app_label || ' | ' || ct.model || ' | Can add ' || ct.model, ct.id, 'add_' || ct.model),
      (ct.app_label || ' | ' || ct.model || ' | Can change ' || ct.model, ct.id, 'change_' || ct.model),
      (ct.app_label || ' | ' || ct.model || ' | Can delete ' || ct.model, ct.id, 'delete_' || ct.model),
      (ct.app_label || ' | ' || ct.model || ' | Can view ' || ct.model, ct.id, 'view_' || ct.model)
    ON CONFLICT (content_type_id, codename) DO NOTHING;
  END LOOP;
END $$;

-- Fake all Django + third-party migrations
INSERT INTO django_migrations (app, name, applied) VALUES
-- Django core
('contenttypes', '0001_initial', NOW()),
('auth', '0001_initial', NOW()),
('auth', '0002_alter_permission_name_max_length', NOW()),
('auth', '0003_alter_user_email_max_length', NOW()),
('auth', '0004_alter_user_username_opts', NOW()),
('auth', '0005_alter_user_last_login_null', NOW()),
('auth', '0006_require_contenttypes_0002', NOW()),
('auth', '0007_alter_validators_add_error_messages', NOW()),
('auth', '0008_alter_user_username_max_length', NOW()),
('auth', '0009_alter_user_last_name_max_length', NOW()),
('auth', '0010_alter_group_name_max_length', NOW()),
('auth', '0011_update_proxy_permissions', NOW()),
('auth', '0012_alter_user_first_name_max_length', NOW()),
('admin', '0001_initial', NOW()),
('admin', '0002_logentry_remove_auto_add', NOW()),
('admin', '0003_logentry_add_action_flag_choices', NOW()),
('sessions', '0001_initial', NOW()),
('sites', '0001_initial', NOW()),
('sites', '0002_alter_domain_unique', NOW()),
-- allauth
('account', '0001_initial', NOW()),
('account', '0002_email_max_length', NOW()),
('account', '0003_email_confirmed_emailaddress_unique', NOW()),
('socialaccount', '0001_initial', NOW()),
('socialaccount', '0002_token_storage', NOW()),
('socialaccount', '0003_extra_data_default_dict', NOW()),
('socialaccount', '0004_app_provider_verbose_name', NOW()),
('socialaccount', '0005_socialaccount_provider_id', NOW()),
-- token_blacklist
('token_blacklist', '0001_squashed_0004_top_to_bigauto', NOW()),
('token_blacklist', '0005_remove_outstandingtoken_jti', NOW()),
('token_blacklist', '0006_migrate_to_bigautofield', NOW()),
('token_blacklist', '0007_migrate_to_bigautofield', NOW()),
('token_blacklist', '0008_migrate_to_bigautofield', NOW()),
('token_blacklist', '0009_migrate_to_bigautofield', NOW()),
('token_blacklist', '0010_migrate_to_bigautofield', NOW()),
('token_blacklist', '0011_migrate_to_bigautofield', NOW()),
('token_blacklist', '0012_migrate_to_bigautofield', NOW()),
-- django_celery_beat
('django_celery_beat', '0001_initial', NOW()),
('django_celery_beat', '0002_auto_20161101_1129', NOW()),
('django_celery_beat', '0003_auto_20161209_0049', NOW()),
('django_celery_beat', '0004_auto_20190516_0412', NOW()),
('django_celery_beat', '0005_auto_20220218_0027', NOW()),
('django_celery_beat', '0006_auto_20240229_1319', NOW()),
('django_celery_beat', '0007_periodictask_timezone', NOW()),
('django_celery_beat', '0008_crontabschedule_timezone', NOW()),
-- Project apps
('users', '0001_add_store_fk_unique_email_store', NOW()),
('users', '0002_uq_platform_admin_email', NOW()),
('users', '0003_platform_user_model', NOW()),
('store', '0001_initial', NOW()),
('store', '0002_uuid_pk_tenant_models', NOW()),
('store', '0003_storesettings_storetheme_branding_fields', NOW()),
('store', '0004_initial', NOW()),
('store', '0005_storesettings_low_stock_threshold', NOW()),
('store', '0006_remove_storetheme_font_family_and_more', NOW()),
('saas', '0001_plan_storesubscription_stubs', NOW()),
('saas', '0002_epic9_plan_subscription_lifecycle', NOW()),
('payment', '0001_mpesa_transaction', NOW()),
('payment', '0002_add_reversal_reason', NOW()),
('payment', '0003_card_transaction', NOW()),
('product', '0001_product_catalog', NOW()),
('order', '0001_order_cartsnapshot', NOW()),
('restaurant', '0001_initial', NOW()),
('restaurant', '0002_add_table', NOW()),
('restaurant', '0003_add_table_session', NOW()),
('restaurant', '0004_add_dineinorder_kitchenticket', NOW()),
('restaurant', '0005_add_pending_order', NOW()),
('restaurant', '0006_add_payment_link', NOW()),
('restaurant', '0007_add_reservation', NOW()),
('restaurant', '0008_add_order_type_pickup_ref', NOW()),
('restaurant', '0009_dineinorder_session_nullable', NOW()),
('restaurant', '0010_add_bill_share', NOW()),
('restaurant', '0011_menuitem_is_age_restricted', NOW()),
('bar', '0001_bar_initial', NOW()),
('analytics', '0001_admin_pii_access_log', NOW()),
('analytics', '0002_analytics_summaries', NOW()),
('notifications', '0001_notifications_initial', NOW()),
('notifications', '0002_fcm_device_model', NOW()),
('loyalty', '0001_loyalty_initial', NOW()),
('contracting', '0001_contracting_initial', NOW())
ON CONFLICT DO NOTHING;

SELECT 'All migrations faked successfully!' AS status;
