# Generated by Django 5.2.17 on 2026-09-03 20:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_order_cartsnapshot"),
        ("payment", "0005_mpesatransaction_payment_mpesa_checkout_idx_and_more"),
        ("store", "0009_store_idx_store_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["store", "created_at"], name="idx_order_store_date"
            ),
        ),
    ]
