# Generated by Django 5.2.17 on 2026-09-03 23:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_order_idx_order_store_date"),
        ("product", "0001_product_catalog"),
        ("store", "0009_store_idx_store_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="coupon_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Applied coupon code (denormalized for reporting).",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Total discount applied from coupon.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Customer-facing code (case-insensitive).",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Internal note — not shown to customers.",
                        max_length=255,
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage off"),
                            ("fixed", "Fixed amount off (KES)"),
                        ],
                        default="percentage",
                        max_length=10,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage (0–100) or fixed amount in KES.",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "min_order_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Minimum cart subtotal to qualify. 0 = no minimum.",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "max_discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cap for percentage discounts. Null = uncapped.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Total redemption limit. Null = unlimited.",
                        null=True,
                    ),
                ),
                ("times_used", models.PositiveIntegerField(default=0)),
                (
                    "max_uses_per_customer",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Per-customer redemption limit. Null = unlimited.",
                        null=True,
                    ),
                ),
                ("valid_from", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "valid_to",
                    models.DateTimeField(
                        blank=True, help_text="Null = no expiry.", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applicable_categories",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Restrict to specific categories. Empty = all categories.",
                        related_name="coupons",
                        to="product.category",
                    ),
                ),
                (
                    "applicable_products",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Restrict to specific products. Empty = all products.",
                        related_name="coupons",
                        to="product.product",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="store.store",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("store", "code"), name="uq_coupon_store_code"
                    )
                ],
            },
        ),
    ]
